fix minor validations and add create table.

diff --git a/dbms b/dbms
--- a/dbms
+++ b/dbms
@@ -1,6 +1,7 @@
 #! /usr/bin/bash
 
-function validateArgument {                                                                                     # add function to validate DataBase_Name
+# Function to validate the database name argument
+function validateArgument {
     if [ -z "$1" ]
     then
         echo "The name field cannot be left empty"
@@ -11,41 +12,49 @@ function validateArgument {                                                     
         return 1
     elif [[ "$1" = *" "* ]]
     then
-      echo "Name Shouldn't Have Spaces"
+        echo "Name Shouldn't Have Spaces"
         return 1
     elif [[ "$1" =~ [^a-zA-Z0-9_] ]]
     then
         echo "Name Shouldn't Have Special Characters"
         return 1
     fi
-    
 }
 
-echo "Hello in your database managment system what would you like to do: "
-select command in CreateDB ListDatabases ConnectToDatabases DropDatabase exit
+echo "Hello! Welcome to your database management system."
+
+# Menu to select database operations
+select command in CreateDB ListDatabases ConnectToDatabases DropDatabase Exit
 do
-case $command in 
-"1" | "CreateDB" )
-	while true
-    do
-    read -p "Enter the name of database you want to create: " dirname 
-	validateArgument $dirname                                                     # write fun validtion and db_name
-	 dirname=$(echo "$dirname" | tr ' ' '_')                                                     # replace space with (_)
-     
-        if [ $? -eq 0 ]                                                            # check if command successed will be exit 
+case $command in
+"CreateDB" )
+        while true
+        do
+            read -p "Enter the name of the database you want to create or 0 to exit: " dirname 
+            if [ "$dirname" = "0" ] 
+            then
+                echo "Exiting..."
+                break
+            fi
+            validateArgument "$dirname"
+            if [ $? -eq 0 ]
+            then
+                dirname=$(echo "$dirname" | tr ' ' '_')
+                break
+            fi
+        done
+        if [ "$dirname" = "0" ] 
         then
             break
         fi
-    done
-        if [ -e $dirname ]
+        if [ -e "$dirname" ]
         then
-            echo "database already exists!"
+            echo "Database '$dirname' already exists!"
         else
             mkdir "$dirname"
-            echo "Database created successfully."
-    fi
-    ;;
-
+            echo "Database '$dirname' created successfully."
+        fi
+        ;;
 "ListDatabases")
     DBS=$(ls -l | grep ^d | cut -d " " -f 9)
     if [[ $DBS ]]
@@ -59,15 +68,24 @@ case $command in
     read -p "Which database would you like to connect to?" dbs
     if [ -e $dbs ]
     then 
-        cd $dbs
+        (./table $dbs)
         echo "Connected to Database "${dbs}
     else
         echo "Database doesn't exist."
     fi
     ;;
 "DropDatabase")
+    while true
+    do
     read -p "Enter the name of database you would like to delete: " dbs
-    if [ -e $dbs ]
+    if [ -z $dbs ]
+    then
+        echo "Invalid input."
+    else
+        break
+    fi
+    done
+    if [ -d $dbs ]
     then
         read -p "Are you sure you want to delete $dbs database! (y/n): " ans
         if [ $ans == "y" ]
@@ -81,7 +99,7 @@ case $command in
         echo "Database doesn't exists."
     fi
     ;;
-"exit")
+"Exit")
     echo "Exiting..."
     break
     ;;
