Adding CreateTable function.

diff --git a/dbms b/dbms
--- a/dbms
+++ b/dbms
@@ -24,36 +24,33 @@ function validateArgument {
 echo "Hello! Welcome to your database management system."
 
 # Menu to select database operations
+PS3="Enter the command number you want: "
 select command in CreateDB ListDatabases ConnectToDatabases DropDatabase Exit
 do
 case $command in
 "CreateDB" )
-        while true
+        flag="false"
+        while [[ $flag == "false" ]]
         do
-            read -p "Enter the name of the database you want to create or 0 to exit: " dirname 
-            if [ "$dirname" = "0" ] 
-            then
+            read -p "Enter the name of the database you want to create or 0 to skip: " dirname 
+            if [ "$dirname" = "0" ]; then
                 echo "Exiting..."
                 break
             fi
             validateArgument "$dirname"
-            if [ $? -eq 0 ]
-            then
+            if [ $? -eq 0 ]; then
                 dirname=$(echo "$dirname" | tr ' ' '_')
-                break
+                if [ -e "./$dirname" ]; then
+                    echo "Database '$dirname' already exists!"
+                else
+                    flag="true"
+                    mkdir ./"$dirname"
+                    echo "Database '$dirname' created successfully."
+                fi
+            else
+                echo "Invalid database name. Please try again."
             fi
         done
-        if [ "$dirname" = "0" ] 
-        then
-            break
-        fi
-        if [ -e "$dirname" ]
-        then
-            echo "Database '$dirname' already exists!"
-        else
-            mkdir "$dirname"
-            echo "Database '$dirname' created successfully."
-        fi
         ;;
 "ListDatabases")
     DBS=$(ls -l | grep ^d | cut -d " " -f 9)
@@ -68,8 +65,8 @@ case $command in
     read -p "Which database would you like to connect to?" dbs
     if [ -e $dbs ]
     then 
-        (./table $dbs)
         echo "Connected to Database "${dbs}
+        (./table $dbs)
     else
         echo "Database doesn't exist."
     fi
@@ -77,13 +74,13 @@ case $command in
 "DropDatabase")
     while true
     do
-    read -p "Enter the name of database you would like to delete: " dbs
-    if [ -z $dbs ]
-    then
-        echo "Invalid input."
-    else
-        break
-    fi
+        read -p "Enter the name of database you would like to delete: " dbs
+        if [ -z $dbs ]
+        then
+            echo "Invalid input."
+        else
+            break
+        fi
     done
     if [ -d $dbs ]
     then
@@ -102,6 +99,9 @@ case $command in
 "Exit")
     echo "Exiting..."
     break
+    ;;
+*)
+    echo "Invalid option. Please try again."
     ;;
 esac
 done
