add update function and select function

diff --git a/table b/table
--- a/table
+++ b/table
@@ -1,7 +1,5 @@
 #! /bin/bash
-
 connectedDbs=$1
-# Function to validate the database name argument
 function validateArgument {
     if [ -z "$1" ]
     then
@@ -22,8 +20,10 @@ function validateArgument {
     fi
 }
 
+# function to create table
+ps3="Enter Option"
 createTable(){
-    local db_dir="$connectedDbs"
+	local db_dir="$connectedDbs"
     local tablename
     local col_name
     local col_type
@@ -103,156 +103,531 @@ createTable(){
         done
     done
 }
-selectFromTable(){                                   #function to select from Table  
-	local tablename 
-	local col_name
-    
-    if [ -z "$(ls)" ]
-    then
-        echo "No Tables To Select From, Table Is Empty."
-        return
-    fi
-    
-    while true
-    do
-        read -p "Enter Table Name: " tablename
-        validateArgument $tablename
-        if [ $? -eq 0 ]
-        then
-            break
-        fi
-    done
-    
-    if [ ! -f "$tablename" ]
-    then
-        echo "Table Doesn't Exist"
-        return
-    fi
-    
-    if [ -s "$$tableName" ]
-    then
-        echo "The $tablename is empty."
-        return
-    fi
-    
-    tail -1 ${tablename}.meta | sed 's/:/\t/g'
-    sed 's/:/\t/g' ${tablename} && echo
-    
+
+# list tables
+ListTables(){
+	output=$(ls ./$connectedDbs)
+			if [[ $output ]]
+			then
+				echo $output
+			else
+				echo "No tables exists yet. "
+			fi
+
+
 }
 
-DropTable(){
-	read -p "Enter the name of the table you want to drop: " tablename
-	if [ -z $tablename ]
-	then
-		echo "Empty input."
-	else
-		if [ -f ./"$connectedDbs/$tablename" ]; then
-			rm ./"$connectedDbs/$tablename"
-			echo "Table '$tablename' has been deleted successfully."
-		else
-			echo "Table '$tablename' does not exist."
-		fi
-	fi
-}
-listTables(){
-	output=$(ls ./$connectedDbs)
-		if [[ $output ]]
-		then
-			echo $output
-		else
-			echo "No tables exists yet. "
-		fi
-}
-UpdateTable(){
-typeset tablename is_pk col_name oldValue newValue colnum
-    
-    if [ -z "$(ls)" ]
-    then
-        echo "No Tables to update it"
+# Function to insert data into the table
+insertIntoTable() {
+    local db_dir="$connectedDbs"
+    local tablename
+    local table_file
+    local schema_file
+    local col_names=()
+    local col_types=()
+    local pk_col
+    local data
+    local pk_value
+    local valid
+
+    read -p "Enter the name of the table to insert into: " tablename
+    tablename=$(echo "$tablename" | tr ' ' '_')
+
+    table_file="$db_dir/$tablename"
+    schema_file="$db_dir/$tablename.meta"
+
+    # Check if table exists
+    if [ ! -e "$table_file" ]; then
+        echo "Table does not exist!"
         return
     fi
-    
-    while true
-    do
-        read -p "Enter Table Name: " tablename
-        validateArgument $tablename
-        if [ $? -eq 0 ]
-        then
+
+     while IFS=: read -r col_name col_type; do
+        # Trim leading and trailing whitespace from column name and type
+        col_name=$(echo "$col_name" | xargs)
+        col_type=$(echo "$col_type" | xargs)
+
+        # Debugging output
+        #echo "Read schema line: '$col_name:$col_type'"
+
+        # Handle primary key
+        if [[ "$col_name" == primary_key* ]]; then
+          	# pk_col=$(grep "primary_key" ./$schema_file | cut -d ":" -f 2)
+            pk_col=$col_type
+        else
+            col_names+=("$col_name")
+            col_types+=("$col_type")
+        fi
+    done < "$schema_file"
+
+    # Prompt user for data
+    while true; do
+        data=()
+        valid=true
+        
+        for i in "${!col_names[@]}"; do
+            read -p "Enter value for ${col_names[$i]} (${col_types[$i]}): " value
+            
+            # Validate data
+            case "${col_types[$i]}" in
+                int)
+					if [[ $((value)) != $value ]]; then
+					        echo "Error: Value '$value' is not a valid integer for column '${col_names[$i]}'."
+                    		valid=false
+                    		break
+					fi
+                    ;;
+                string)
+                    if [ -z $value ]
+                    then
+                        echo "empty input,try again."
+                        valid=false
+                        break
+                    else
+                        if [[ ! $value =~ [a-zA-Z]* ]]
+                        then
+                            echo "invalid string."
+                            valid=false
+                            break
+                        fi
+                    fi
+                    ;;
+                *)
+                    echo "Error: Unknown data type '${col_types[$i]}' for column '${col_names[$i]}'."
+                    valid=false
+                    break
+                    ;;
+            esac
+            data+=("$value")
+        done
+        
+        if [ "$valid" = true ]; then
+            # Check if primary key value is unique
+            if [[ -n "$pk_col" ]]; then
+                echo "${col_names[@]}"
+                pk_index=$(echo "${col_names[@]}" | tr ' ' '\n' | grep -n "^$pk_col$" | cut -d: -f1)
+                echo "$pk_index"
+                pk_value="${data[$((pk_index - 1))]}"
+
+                echo "Checking for primary key value: $pk_col:$pk_value"
+
+                if grep "${pk_col}:${pk_value}" "$table_file"; then
+                    echo "Error: Primary key value '$pk_value' already exists."
+                    continue
+                fi
+            fi
+
+            line=""
+            for i in "${!col_names[@]}"
+            do
+                line+="${col_names[$i]}:${data[$i]},"
+            done
+            # Remove the trailing comma
+            line=${line%,}
+            echo "$line"
+            echo "$line" >> "$table_file"
+            
+            echo "Data inserted successfully."
+        fi
+
+        read -p "Do you want to insert more rows? (yes/no): " more
+        if [[ "$more" != "yes" ]]; then
+            echo "Finished inserting rows."
+            return
+        fi
+    done
+}
+# Function to select data from the table
+selectFromTable() {
+    local db_dir="$connectedDbs"
+    local tablename
+    local table_file
+    local schema_file
+    local col_names=()
+    local col_types=()
+    local pk_col
+    local select_col
+    local select_val
+    local line
+
+    while true; do
+        read -p "Enter the name of the table to select from: " tablename
+        if ! validateArgument "$tablename"; then
+            continue
+        fi
+        tablename=$(echo "$tablename" | tr ' ' '_')
+        
+        table_file="$db_dir/$tablename"
+        schema_file="$db_dir/$tablename.meta"
+
+        # Check if table exists
+        if [ ! -e "$table_file" ]; then
+            echo "Table '$tablename' does not exist!"
+            continue
+        fi
+
+        # Read schema to get column names and types using delemater (:)      
+        while IFS=: read -r col_name col_type; do                               
+            # Trim leading and trailing whitespace from column name and type and can read it from user
+            col_name=$(echo "$col_name" | xargs)
+            col_type=$(echo "$col_type" | xargs)
+
+            # Handle primary key
+            if [[ "$col_name" == primary_key* ]]; then
+                pk_col=$col_type
+            else
+                col_names+=("$col_name")
+                col_types+=("$col_type")
+            fi
+        done < "$schema_file"
+
+        break
+    done
+
+    # Prompt user for column and value to select
+    while true; do
+    read -p "Enter the column name to select (leave blank to select all): " select_col
+    if [[ -n "$select_col" ]]; then
+        # Validate column name
+        if ! validateArgument "$select_col"; then
+            continue
+        fi
+        # Check if column exists in schema
+        if ! [[ " ${col_names[@]} " =~ " $select_col " ]]; then
+            echo "Column '$select_col' does not exist in the table."
+            continue
+        fi
+    fi
+
+    read -p "Enter the value to select (leave blank to select all): " select_val
+    # Validate value
+    if [[ -n "$select_val" ]]; then
+        # Trim leading and trailing whitespace
+        select_val=$(echo "$select_val" | xargs)
+        # Validate if value is empty after trimming
+        if [[ -z "$select_val" ]]; then
+            echo "Invalid input. Value cannot be empty after trimming."
+            break
+        fi
+    fi
+
+    # Print column headers
+    printf "%s\t" "${col_names[@]}"
+    echo # New line
+
+    # Read each line from the table file
+    while IFS=, read -r line; do
+        # Check if line matches selection criteria
+        if [[ -z "$select_col" || -z "$select_val" || $(echo "$line" | grep -w "$select_col:$select_val") ]]; then
+            # Split line into columns
+            IFS=',' read -r -a columns <<< "$line"
+            for col in "${columns[@]}"; do
+                # Print each column value
+                printf "%s\t" "$col"
+            done
+            echo # New line
+        fi
+    done < "$table_file"
+
+    while true; do
+        read -p "Do you want to select more data? (yes/no): " more
+        case "$more" in
+            yes)
+                break ;;
+            no)
+                echo "Finished selecting data."
+                return ;;
+            *)
+                echo "Invalid input. Please enter 'yes' or 'no'."
+                ;;
+        esac
+    done
+done     
+}
+
+# Function to update data in the table for a selected column
+updateTable() {
+    local db_dir="$connectedDbs"
+    local tablename
+    local table_file
+    local schema_file
+    local col_names=()
+    local col_types=()
+    local pk_col
+    local update_col
+    local update_val
+    local pk_val
+    local line
+    local temp_file="/tmp/update_temp.$$"
+
+    while true; do
+        read -p "Enter the name of the table to update: " tablename
+        if ! validateArgument "$tablename"; then
+            continue
+        fi
+        tablename=$(echo "$tablename" | tr ' ' '_')
+
+        table_file="$db_dir/$tablename"
+        schema_file="$db_dir/$tablename.meta"
+
+        # Check if table exists
+        if [ ! -e "$table_file" ]; then
+            echo "Table '$tablename' does not exist!"
+            continue
+        fi
+
+        # Read schema to get column names and types
+        while IFS=: read -r col_name col_type; do
+            # Trim leading and trailing whitespace from column name and type
+            col_name=$(echo "$col_name" | xargs)
+            col_type=$(echo "$col_type" | xargs)
+
+            # Handle primary key
+            if [[ "$col_name" == primary_key* ]]; then
+                pk_col=$col_type
+            else
+                col_names+=("$col_name")
+                col_types+=("$col_type")
+            fi
+        done < "$schema_file"
+
+        break
+    done
+
+    # Prompt user for primary key value to update
+    while true; do
+        read -p "Enter the value of the primary key to update: " pk_val
+        # Check if the primary key value exists in the table
+        if ! grep -q "${pk_col}:${pk_val}" "$table_file"; then
+            echo "Primary key value '$pk_val' does not exist in the table."
+            continue
+        else
             break
         fi
     done
-    
-    if [ ! -f "$tablename" ]
-    then
-        echo "${tablename} Doesn't Exist"
-        return
-    fi
-    
-    if [ -z "$(cat "$tablename")" ]
-    then
-        echo "The $tablename is empty."
-        return
-    fi
-    
-    read -p "Enter Primary key : " is_pk
-    
-    if [ -z "$(grep ^${is_pk} ${tablename})" ]
-    then
-        echo "The primary key doesn't Exist"
-        return
-    fi
-    
-    read -p "Enter column name: " colName
-    
-    if [ -z "$(grep ${col_name} ${tablename}.meta)" ]
-    then
-        echo "The ${col_name} column doesn't Exist"
-        return
-    fi
-    
-    colnum=$(awk -F: '{ for (i=1; i<=NF; i++) { if ($i == "'"$col_name"'") { print i; exit } } }' ${tablename}.meta)
-    oldValue=$( grep "^${is_pk}" ${tablename} | cut -d ':' -f $colnum )
-    
-    read -p "Enter new value: " newValue
-    
-    sed -i "/^$pkValue/s/$oldValue/$newValue/" ${tableName}
+
+    # Prompt user for column to update
+    while true; do
+        read -p "Enter the column name to update: " update_col
+        if ! validateArgument "$update_col"; then
+            continue
+        fi
+        # Validate column name
+        if ! [[ " ${col_names[@]} " =~ " $update_col " ]]; then
+            echo "Column '$update_col' does not exist in the table."
+            continue
+        else
+            break
+        fi
+    done
+
+    # Prompt user for new value
+    read -p "Enter the new value for column '$update_col': " update_val
+
+    # Perform the update operation
+    awk -v col_name="$update_col" -v col_val="$update_val" -v pk_col="$pk_col" -v pk_val="$pk_val" -F ',' '{
+        if ($1 == pk_col ":" pk_val) {
+            for (i = 2; i <= NF; i++) {
+                split($i, arr, ":")
+                if (arr[1] == col_name) {
+                    $i = col_name ":" col_val
+                    break
+                }
+            }
+        }
+        print $0
+    }' "$table_file" > "$temp_file" && mv "$temp_file" "$table_file"
+
+    echo "Updated column '$update_col' with value '$update_val' where primary key '$pk_col' is '$pk_val'."
+    echo "Update Success."
 }
-DeleteFromTable(){
-echo "delete"
+
+
+deleteFromTable() {
+    local db_dir="$connectedDbs"
+    local table_file
+    local schema_file
+    local col_names=()
+    local col_types=()
+    local pk_col
+    local value
+    local pk_value
+
+    tablename=""
+    read -p "Enter the name of the table to delete from: " tablename
+    tablename=$(echo "$tablename" | tr ' ' '_')
+
+    table_file="$db_dir/$tablename"
+    schema_file="$db_dir/$tablename.meta"
+
+    # Check if table exists
+    if [ -z "$tablename" ]
+    then
+        echo "Empty input"
+        return
+    fi
+    if [ ! -e "$table_file" ]; then
+        echo "Table does not exist!"
+        return
+    fi
+
+    # Read schema file and determine the columns and types
+    while IFS=: read col_name col_type; do
+        if [[ "$col_name" == primary_key* ]]; then
+            pk_col="${col_type}"
+        else
+            col_names+=("$col_name")
+            col_types+=("$col_type")
+        fi
+    done < "$schema_file"
+
+    # Display menu options
+    echo "Select deletion option:"
+    echo "1) Delete by ID (Primary Key)"
+    echo "2) Delete by Column"
+    echo "3) Delete All Rows"
+    read -p "Enter your choice (1/2/3): " delete_option
+
+    case "$delete_option" in
+    1)
+        # Delete by ID (Primary Key)
+        if [[ -z "$pk_col" ]]; then
+            echo "Error: No primary key defined for this table."
+            return
+        fi
+        
+        read -p "Enter the primary key value to delete: " pk_value
+
+        deletedRow="$column_name:$value"
+        tableFile="./$connectedDbs/$tablename"
+        
+        grep "$deletedRow" $tableFile
+        if [ $? == 1 ]; then
+            echo "No matching rows found to delete."
+            return
+        fi
+
+        sed -i "/$deletedRow/d" "$tableFile"        
+        echo "Matching rows has been Deleted."
+        ;;
+    2)
+        # Delete by Column
+        read -p "Enter the column name to filter by: " column_name
+
+        if ! [[ " ${col_names[@]} " =~ " $column_name " ]]; then
+                echo "Error: Column '$column_name' does not exist."
+                return
+        fi
+
+        read -p "Enter the value to filter by: " value
+
+        # Validate the value based on the column type
+        column_index=$(echo "${col_names[@]}" | tr ' ' '\n' | grep -n "^$column_name$" | cut -d: -f1)
+        column_index=$((column_index - 1))
+        column_type="${col_types[$column_index]}"
+
+        case "$column_type" in
+            int)
+                if ! [[ "$value" =~ ^[0-9]+$ ]]; then
+                    echo "Error: Value for column '$column_name' must be an integer."
+                    return
+                fi
+                ;;
+            string)
+                if [[ -z "$value" ]]; then
+                    echo "Error: Value for column '$column_name' must not be empty."
+                    return
+                fi
+                ;;
+            *)
+                echo "Error: Unknown data type for column '$column_name'."
+                return
+                ;;
+        esac
+
+
+        deletedRow="$column_name:$value"
+        tableFile="./$connectedDbs/$tablename"
+        
+        grep "$deletedRow" $tableFile
+        if [ $? == 1 ]; then
+            echo "No matching rows found to delete."
+            return
+        fi
+
+        sed -i "/$deletedRow/d" "$tableFile"        
+        echo "Matching rows has been Deleted."
+    ;;
+    3)
+        # Delete All Rows
+        > "$table_file"
+        echo "All rows have been deleted."
+        return
+        ;;
+    *)
+        echo "Invalid option selected."
+        return
+        ;;
+    esac
+}
+#DropTable
+DropTable(){
+		read -p "Enter the name of the table you want to drop: " tablename
+		
+		tablename=$(echo "$tablename" | tr ' ' '_')
+
+	    if [[ ! "$tablename" =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
+		echo "Invalid table name. It should start with a letter and contain only letters, numbers, and underscores."
+		return
+	    fi
+		if [ -z $tablename ]
+		then
+			echo "Empty input."
+		else
+			if [ -f ./"$connectedDbs/$tablename" ]; then
+				rm ./"$connectedDbs/$tablename"
+				echo "Table '$tablename' has been deleted successfully."
+			else
+				echo "Table '$tablename' does not exist."
+			fi
+		fi
+
 }
 
 echo "Hello in your $connectedDbs database what would you like to do: "
-select command in CreateTable ListTables DropTable InsertIntoTables SelectFromTable UpdateTable DeleteFromTable QuitFromDB
+select command in CreateTable ListTables DropTable InsertIntoTables SelectTable UpdateTable DeleteFromTable QuitFromDB
 do
 case $command in 
 "CreateTable" )
-		createTable
+	       createTable
     ;;
 "ListTables")
-		listTables
+		ListTables
 ;;
 "DropTable")
-		DropTable
-	
+	DropTable
 	;;
 "InsertIntoTables")
-	insertIntoTable
+	   insertIntoTable
 ;;
 
-"SelectFromTable")
-   		selectFromTable
+"SelectTable")
+             selectFromTable
 ;;
+
 
 "UpdateTable")
-		UpdateTable
+             updateTable
 
 ;;
-"DeleteFromTable ")
-		DeleteFromTable
+"DeleteFromTable")
+                 deleteFromTable
 ;;
 "QuitFromDB")
 	echo "Exiting from $connectedDbs database. "
-	break 
+	     break
+	     
+	     
 ;;
 *)
 echo "Invalid Selection"
